### ISSUE TITLE
Version 2.2.0: Failed to load next.config.js. TypeError: withImageLoader is not a function.

### ISSUE THREAD

**Issue by goguda** [aiji42/next-image-loader#140]
![image](https://user-images.githubusercontent.com/26887502/177794170-2421f79c-e8a3-47f6-86dd-f2d8f0f76d68.png)

As the title says. Cannot run the Next.js dev server since upgrading to 2.2.0. Downgrading to 2.1.0 the issue is fixed.

Latest Next.js version, 12.2.0.

**Comment by goguda** [comment]
> See https://github.com/aiji42/next-image-loader/releases/tag/v2.2.0.

Ah ok. Switched and it's working fine now. Sorry about that, should have checked the release notes before opening an issue. Thank you!
